spring:
  config:
    import: 
      - optional:file:.env[.properties]  # Tells Spring Boot to natively parse your root .env file

  security:
    oauth2:
      client:
        registration:
            google:
                client-id: sdkfjakjfsdk
                client-secret: sgjfreijtrig
            github:
                client-id: ${GITHUB_CLIENT_ID}
                client-secret: ${GITHUB_CLIENT_SECRET}