spring.application.name=hospitalmanagement

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

jwt.secretKey=kfsdjfklnsdafuerawkjhfgiuwr478r564398562gf7384tfg8ysefg3478ogfuiewgf734ir