spring.config.import=optional:file:.env[.properties]

spring.application.name=hospitalmanagement

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql

jwt.secretKey=${JWT_SECRET}

spring.data.redis.host=localhost
spring.data.redis.port=6379